all:
	@echo "executable name: assignment1"
	@g++ -o assignment1 main.cpp ground.cpp player.cpp wall.cpp maze.cpp enemy.cpp coins.cpp obstacles.cpp firstaid.cpp battery.cpp godeye.cpp -lGL -lGLU -lglut
clean:
	@find . -maxdepth 1 -type f -executable -exec rm {} +